version: '3.3'
services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring
networks:
  monitoring:
    external: true
