version: "3.8"

networks:
  monitoring:
    external: true

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports: ["80:80"]
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks: [monitoring]