version: "3.8"

networks:
  monitoring:
    external: true

services:
  fastapi_app:
    build: .               # или image: your/imagename:tag
    container_name: fastapi_app
    ports: ["80:80"]       # наружу, если нужно
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks: [monitoring]